In [3]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive
/gdrive


## Uploading the Dataset

In [4]:

from bs4 import BeautifulSoup
from textblob import TextBlob
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
import pandas as pd 

#Label and file details load
df = pd.read_csv('/gdrive/My Drive/Machine Learning /master996.csv', header = None, encoding='latin1')
csvInput = df.values.tolist()

#Please change file path
file_path = '/gdrive/My Drive/Gutenberg_19th_century_English_Fiction'

print(csvInput)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[['Book_Name;book_id;guten_genre;Author_Name'], ['The Mystery of the Boule Cabinet: A Detective Story;pg10067.epub;Detective and Mystery;Stevenson| Burton Egbert'], ['The Pupil;pg1032.epub;Literary;James| Henry'], ["At Love's Cost;pg10379.epub;Literary;Garvice| Charles"], ['The Heart of the Range;pg10473.epub;Western Stories;White| William Patterson'], ['The Worshipper of the Image;pg10812.epub;Literary;Gallienne| Richard Le'], ['The Book-Bills of Narcissus - An Account Rendered by Richard Le Gallienne;pg10826.epub;Literary;Gallienne| Richard Le'], ['Elusive Isabel;pg10943.epub;Detective and Mystery;Futrelle| Jacques'], ["Joe Burke's Last Stand;pg11004.epub;Literary;Wetterau| John Moncure"], 

In [ ]:
import os
os.chdir("/content")
os.getcwd()

'/content'

## Feature Extraction from the Books

In [ ]:

pr_list = [] 
feature_list = []  
#Please change file path
file_path = '/gdrive/My Drive/Gutenberg_19th_century_English_Fiction'
import os
os.chdir("/content")
pr_list = [] 
feature_list = []
personal_pronoun = 0
male_pronoun = ['He', 'His', 'Him', 'Himself']
male_pronoun_count = 0 
female_pronoun = ['She','Her','Hers', 'Herself']
female_pronoun_count = 0
possessive_pronoun = ['Mine','Yours','Hers', 'His', 'Ours', 'Yours', 'Theirs']
possessive_pronoun_count  = 0
paragraph_count = 0
prepositions = 0
cordinating_conjunction = ['For', 'And', 'Nor', 'But', 'Or', 'Yet', 'So']
conjuction_count = 0
books  = 0
index = 0
for book_details in csvInput:
    if index == 0:
      index = index + 1
      continue
    print(book_details)
    #Getting the file name from CSV
    a_split = book_details[0].split(';')
    file_name = a_split[1]
    if "." in a_split[1]:
      file_name = file_name.split('.')[0]
    #attaching the filename to filepath
    file_path_new = file_path +'/'+ file_name + '-content.html'
    #Loading HTML content
    html = open(file_path_new, encoding="UTF-8").read()
    soup = BeautifulSoup(html, features="lxml")
    all_p = soup.find_all('p')
    
    
    #Extracting feature of pronouns - Counts of pronouns
    for p in all_p:
      wiki = TextBlob(p.getText())
      string = str(wiki)
      colon = string.count(":")
      semicolon = string.count(";")
      hypen = string.count("-")
      interjection = string.count("!")
      comma = string.count(",")
      period = string.count(".")


      paragraph_count = paragraph_count + 1

      for word in wiki.tags:

        if word[1] == 'PRP' or word[1] == 'PRP$':
          personal_pronoun = personal_pronoun + 1

        if word[0] in male_pronoun:
          male_pronoun_count = male_pronoun_count + 1

        if word[0] in female_pronoun:
          female_pronoun_count = female_pronoun_count + 1

        if word[0] in possessive_pronoun:
          possessive_pronoun_count = possessive_pronoun_count + 1
        
        if word[0] in cordinating_conjunction:
          conjuction_count = conjuction_count + 1

        if word[1] in ['IN']:
          prepositions = prepositions + 1



    # New features extraction need to be added here
    #Adding pronoun count and Label to list 
    pr_list.append(paragraph_count)
    pr_list.append(female_pronoun_count)
    pr_list.append(male_pronoun_count)
    pr_list.append(personal_pronoun)
    pr_list.append(possessive_pronoun_count)
    pr_list.append(conjuction_count)
    pr_list.append(prepositions)
    pr_list.append(comma)
    pr_list.append(period)
    pr_list.append(colon)
    pr_list.append(semicolon)
    pr_list.append(hypen)
    pr_list.append(interjection)

    if a_split[2] == "Literary":
      pr_list.append(1)
    elif a_split[2] == "Detective and Mystery":
      pr_list.append(2)
    elif a_split[2] == "Western Stories":
      pr_list.append(3)   
    elif a_split[2] == "Ghost and Horror":
      pr_list.append(4)  
    elif a_split[2] == "Humorous and Wit and Satire":
      pr_list.append(5)
    elif a_split[2] == "Christmas Stories":
      pr_list.append(6)
    elif a_split[2] == "Love and Romance":
      pr_list.append(7)
    elif a_split[2] == "Sea and Adventure":
      pr_list.append(8)
    elif a_split[2] == "Allegories":
      pr_list.append(9)
    elif a_split[2] == "All":
      pr_list.append(10)


    print(pr_list)
    feature_list.append(pr_list)
    pr_list = []
    personal_pronoun = 0
    male_pronoun_count = 0 
    female_pronoun_count = 0
    possessive_pronoun_count  = 0
    paragraph_count = 0
    prepositions = 0
    conjuction_count = 0
    

    #if(books == 3):
   
print(feature_list)
# Printing features to CSV
outputDataFrame = pd.DataFrame(feature_list, columns=['f0','f1','f2','f3','f4','f6','f5','f7','f8','f9','f10','f11','f12','label'])
output_file_path = 'feature.csv'
outputDataFrame.to_csv(output_file_path, index =  True, header=True, encoding="utf-8") 


## Feature Scaling

In [2]:
#from sklearn.preprocessing import MinMaxScalar
from sklearn.preprocessing import StandardScaler
import pandas as pd
dataset = pd.read_csv('/content/feature.csv')

data = dataset.iloc[0:,1:-1]
label = dataset.iloc[0:,-1]

sc = StandardScaler()
data = sc.fit_transform(data)
data


array([[ 0.44962041, -0.8563035 ,  0.03601265, ..., -0.18264687,
        -0.47613168,  1.05742491],
       [-1.3154065 , -0.8706005 , -0.9765783 , ..., -0.18264687,
        -0.47613168, -0.38927181],
       [ 1.52440354,  1.63614099,  1.16299672, ...,  0.24438665,
        -0.47613168, -0.38927181],
       ...,
       [ 0.25078115, -0.69427078,  0.1419322 , ..., -0.18264687,
        -0.47613168, -0.38927181],
       [ 0.66860637, -0.14145326, -0.21819428, ..., -0.18264687,
         0.93107055, -0.38927181],
       [-1.21204512, -0.92302285, -1.06555073, ..., -0.18264687,
        -0.47613168, -0.38927181]])

## Splitting into train and test

In [69]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, label, test_size=0.33, random_state=45)

In [4]:
x_train.shape

(667, 13)

## Combining Training data with its labels

In [73]:
import numpy as np
x_train = np.array(x_train)
y_train = np.array(y_train)

train_data = np.column_stack((x_train, y_train))
train_data.shape

train_data = pd.DataFrame(train_data)

#train_data = np.concatenate((x_train,y_train), axis = 0)

#pd.concat([x_train, pd.DataFrame(y_train)])
train_data

0         1         2         3   ...        10        11        12   13
0    0.588020  0.649648  0.226668  1.302164  ... -0.182647 -0.476132 -0.389272  1.0
1   -0.315955 -0.365440  0.124985 -0.698457  ... -0.182647 -0.476132 -0.389272  8.0
2   -0.968533 -0.956383 -0.942684 -0.691363  ... -0.182647 -0.476132  1.057425  1.0
3   -1.007950 -0.903960 -1.184181 -0.401037  ...  0.671420 -0.476132 -0.389272  8.0
4   -0.688231 -0.327314 -0.730845  0.107293  ... -0.182647  0.227469 -0.389272  1.0
..        ...       ...       ...       ...  ...       ...       ...       ...  ...
662  2.200632 -0.098562 -0.065670  0.923425  ... -0.182647 -0.476132 -0.389272  1.0
663  0.804378  2.879980  1.684121  2.402220  ... -0.182647 -0.476132 -0.389272  1.0
664 -0.069814  0.196909 -0.413086 -0.050673  ...  0.244387 -0.476132 -0.389272  1.0
665  0.565245 -0.818178 -0.442744  1.394902  ... -0.182647 -0.476132 -0.389272  1.0
666 -0.875683 -0.846772 -0.514769 -0.698630  ... -0.182647  0.227469 -0.389272  2.0

[667 rows x 14 columns]

## Tackling Class Imbalance

In [74]:
Lit = train_data[train_data[13] ==1]
D_M = train_data[train_data[13] ==2]
W_S = train_data[train_data[13] ==3]
G_H = train_data[train_data[13] ==4]
H_W_S = train_data[train_data[13] ==5]
C_S = train_data[train_data[13] ==6]
L_R = train_data[train_data[13] ==7]
S_A = train_data[train_data[13] ==8]
A_L = train_data[train_data[13] ==9]

Lit[13] = 1
Lit

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()


0         1         2         3   ...        10        11        12  13
0    0.588020  0.649648  0.226668  1.302164  ... -0.182647 -0.476132 -0.389272   1
2   -0.968533 -0.956383 -0.942684 -0.691363  ... -0.182647 -0.476132  1.057425   1
4   -0.688231 -0.327314 -0.730845  0.107293  ... -0.182647  0.227469 -0.389272   1
5   -0.067186  0.211206  2.434031 -0.236842  ... -0.182647 -0.476132  2.504122   1
6    1.586596 -0.903960 -0.442744  0.688811  ... -0.182647 -0.476132 -0.389272   1
..        ...       ...       ...       ...  ...       ...       ...       ...  ..
661 -0.358000 -0.184344 -0.535953 -0.116939  ... -0.182647 -0.476132 -0.389272   1
662  2.200632 -0.098562 -0.065670  0.923425  ... -0.182647 -0.476132 -0.389272   1
663  0.804378  2.879980  1.684121  2.402220  ... -0.182647 -0.476132 -0.389272   1
664 -0.069814  0.196909 -0.413086 -0.050673  ...  0.244387 -0.476132 -0.389272   1
665  0.565245 -0.818178 -0.442744  1.394902  ... -0.182647 -0.476132 -0.389272   1

[534 rows x 14 columns]

In [75]:
from sklearn.utils import resample
import sys

D_M_upsampled = resample(D_M, 
                                 replace=True,     # sample with replacement
                                 n_samples=534,    # to match majority class
                                 random_state=123)
D_M_upsampled[13] = 2

########################
W_S_upsampled = resample(W_S, 
                                 replace=True,     # sample with replacement
                                 n_samples=534,    # to match majority class
                                 random_state=123)
W_S_upsampled[13] = 3

######################

G_H_upsampled = resample(G_H, 
                                 replace=True,     # sample with replacement
                                 n_samples=534,    # to match majority class
                                 random_state=123)
G_H_upsampled[13] = 4

#######################

H_W_S_upsampled = resample(H_W_S, 
                                 replace=True,     # sample with replacement
                                 n_samples=534,    # to match majority class
                                 random_state=123)
H_W_S_upsampled[13] = 5

#######################

C_S_upsampled = resample(C_S, 
                                 replace=True,     # sample with replacement
                                 n_samples=534,    # to match majority class
                                 random_state=123)
C_S_upsampled[13] = 6

####################

L_R_upsampled = resample(L_R, 
                                 replace=True,     # sample with replacement
                                 n_samples=534,    # to match majority class
                                 random_state=123)
L_R_upsampled[13] = 7

#####################

S_A_upsampled = resample(S_A, 
                                 replace=True,     # sample with replacement
                                 n_samples=534,    # to match majority class
                                 random_state=123)
S_A_upsampled[13] = 8

########################

A_L_upsampled = resample(A_L, 
                                 replace=True,     # sample with replacement
                                 n_samples=534,    # to match majority class
                                 random_state=123)
A_L_upsampled[13] = 9

A_L_upsampled


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation:

0         1         2         3   ...       10        11        12  13
538 -0.120619  0.068236  0.091091 -0.382351  ...  0.67142  1.634672 -0.389272   9
538 -0.120619  0.068236  0.091091 -0.382351  ...  0.67142  1.634672 -0.389272   9
538 -0.120619  0.068236  0.091091 -0.382351  ...  0.67142  1.634672 -0.389272   9
538 -0.120619  0.068236  0.091091 -0.382351  ...  0.67142  1.634672 -0.389272   9
538 -0.120619  0.068236  0.091091 -0.382351  ...  0.67142  1.634672 -0.389272   9
..        ...       ...       ...       ...  ...      ...       ...       ...  ..
538 -0.120619  0.068236  0.091091 -0.382351  ...  0.67142  1.634672 -0.389272   9
538 -0.120619  0.068236  0.091091 -0.382351  ...  0.67142  1.634672 -0.389272   9
538 -0.120619  0.068236  0.091091 -0.382351  ...  0.67142  1.634672 -0.389272   9
538 -0.120619  0.068236  0.091091 -0.382351  ...  0.67142  1.634672 -0.389272   9
538 -0.120619  0.068236  0.091091 -0.382351  ...  0.67142  1.634672 -0.389272   9

[534 rows x 14 columns]

## Concatinating the upsampled classes

In [76]:
frame = [Lit, D_M_upsampled,W_S_upsampled, G_H_upsampled, H_W_S_upsampled, C_S_upsampled,L_R_upsampled,S_A_upsampled, A_L_upsampled]
train_data = pd.concat(frame)

x_train = train_data.iloc[0:, 0:-1]
y_train = train_data.iloc[0:,-1]

x_test = pd.DataFrame(x_test)
x_test = x_test.iloc[0:, 0:13]

print(x_train.shape)
print(x_test.shape)

(4806, 13)
(329, 13)


## Training an SVM model

In [77]:
from sklearn.svm import SVC
from sklearn import metrics

non_linear_svm = SVC(kernel='linear')

non_linear_svm.fit(x_train, y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

## Testing the model

In [78]:
svm_pred = non_linear_svm.predict(x_test)
svm_score = metrics.accuracy_score(y_test, svm_pred)
print(svm_score)

0.3556231003039514


## Model Selection

In [ ]:
from sklearn.model_selection import GridSearchCV

parameters = [{'C':[1,10,100,100], 'kernel': ['linear']},
               {'C':[1,10,100,100], 'kernel': ['rbf'], 'gamma': [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]},
                {'C':[1,10,100,100], 'kernel': ['poly']} ]

grid_search = GridSearchCV(estimator=non_linear_svm,
                           param_grid= parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search.fit(x_train,y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 100], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 100],
                          'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
                                    0.9],
                          'kernel': ['rbf']},
                         {'C': [1, 10, 100, 100], 'kernel': ['poly']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [ ]:
grid_search.best_params_

{'C': 100, 'gamma': 0.9, 'kernel': 'rbf'}

## Training the model with Best parameters

In [79]:
from sklearn.svm import SVC
from sklearn import metrics

non_linear_svm = SVC(C = 100, kernel='rbf', gamma=0.9)

non_linear_svm.fit(x_train, y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.9, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

## Evaluating the results on the Test set

In [80]:
svm_pred = non_linear_svm.predict(x_test)
svm_score = metrics.accuracy_score(y_test, svm_pred)
print(svm_score)

0.7629179331306991


In [81]:
from sklearn.metrics import classification_report
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           1       0.81      0.93      0.87       260
           2       0.36      0.27      0.31        33
           3       1.00      0.12      0.22         8
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         8
           8       0.00      0.00      0.00        16
           9       0.00      0.00      0.00         1

    accuracy                           0.76       329
   macro avg       0.24      0.15      0.16       329
weighted avg       0.70      0.76      0.72       329



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Confusion Matrix

In [14]:
import matplotlib.pyplot as plt
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, svm_pred)

print(cm)


[[241  13   0   4   0   2   0   0   0]
 [ 23   9   0   0   0   0   1   0   0]
 [  6   1   1   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  7   1   0   0   0   0   0   0   0]
 [ 16   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0]]


#Feature Selection

In [91]:
from sklearn.feature_selection import SelectKBest, chi2, f_classif

anova = SelectKBest(f_classif, k=8)
x_train_anova = anova.fit_transform(x_train, y_train)
x_test_anova = anova.transform(x_test)

#Model Selection

In [ ]:
from sklearn.model_selection import GridSearchCV

parameters = [{'C':[1,10,100], 'kernel': ['linear']},
               {'C':[1,10,100], 'kernel': ['rbf'], 'gamma': [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]},
                {'C':[1,10,100], 'kernel': ['poly'], 'degree': [1,2,3,4,5,6]} ]

grid_search = GridSearchCV(estimator=non_linear_svm,
                           param_grid= parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search.fit(x_train_anova,y_train)

## Model training and Evaluation

In [83]:
from sklearn.svm import SVC
from sklearn import metrics

non_linear_svm = SVC(C = 100, kernel='rbf', gamma=0.9)

non_linear_svm.fit(x_train_anova, y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.9, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [84]:
svm_pred = non_linear_svm.predict(x_test_anova)
svm_score = metrics.accuracy_score(y_test, svm_pred)
print(svm_score)

0.6899696048632219


#Confusion Matrix

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, svm_pred)

print(cm)

[[217  27   2   2   0   4   0   8   0]
 [ 23   7   1   0   1   0   1   0   0]
 [  5   2   1   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]
 [  6   1   0   0   0   0   1   0   0]
 [ 13   2   0   0   0   0   0   1   0]
 [  1   0   0   0   0   0   0   0   0]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           1       0.81      0.83      0.82       260
           2       0.17      0.21      0.19        33
           3       0.25      0.12      0.17         8
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         0
           7       0.50      0.12      0.20         8
           8       0.11      0.06      0.08        16
           9       0.00      0.00      0.00         1

    accuracy                           0.69       329
   macro avg       0.21      0.15      0.16       329
weighted avg       0.68      0.69      0.68       329



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Random Forest


In [49]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
rf.fit(x_train_anova, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [52]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [10,50, 100, 200, 300],
    'criterion': ['entropy','gini']
    
}
# Create a based model
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 10, n_jobs = -1, verbose = 2)
grid_search.fit(x_train,y_train)

Fitting 10 folds for each of 720 candidates, totalling 7200 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:   11.6s
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 361 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-1)]: Done 644 tasks      | elapsed:  4.8min
[Parallel(n_jobs=-1)]: Done 1009 tasks      | elapsed:  7.7min
[Parallel(n_jobs=-1)]: Done 1454 tasks      | elapsed: 11.1min
[Parallel(n_jobs=-1)]: Done 1981 tasks      | elapsed: 15.2min
[Parallel(n_jobs=-1)]: Done 2588 tasks      | elapsed: 20.0min
[Parallel(n_jobs=-1)]: Done 3277 tasks      | elapsed: 25.3min
[Parallel(n_jobs=-1)]: Done 4046 tasks      | elapsed: 30.6min
[Parallel(n_jobs=-1)]: Done 4897 tasks      | elapsed: 35.7min
[Parallel(n_jobs=-1)]: Done 5828 tasks      | elapsed: 41.2min
[Parallel(n_jobs=-1)]: Done 6841 tasks      | elapsed: 47.3min
[Parallel(n_jobs=-1)]: Done 7200 out of 7200 | elapsed: 49.6min finished


GridSearchCV(cv=10, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='entropy',
                                              max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=10, n_jobs=None,
                                              oob_score=False, ra

In [53]:
grid_search.best_params_

{'bootstrap': True,
 'criterion': 'gini',
 'max_depth': 80,
 'max_features': 2,
 'min_samples_leaf': 3,
 'min_samples_split': 8,
 'n_estimators': 200}

In [96]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators = 200, criterion = 'gini',bootstrap = True, max_depth=80, max_features=2, min_samples_leaf =3,min_samples_split=8,random_state=True)
rf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=80, max_features=2,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=8,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=True,
                       verbose=0, warm_start=False)

## Evaluating of Random Forest

In [97]:
rf_pred = rf.predict(x_test)
rf_score = metrics.accuracy_score(y_test, rf_pred)
print(rf_score)

0.7811550151975684


In [98]:
from sklearn.metrics import classification_report
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           1       0.82      0.95      0.88       260
           2       0.38      0.24      0.30        33
           3       0.00      0.00      0.00         8
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         8
           8       0.33      0.06      0.11        16
           9       0.00      0.00      0.00         1

    accuracy                           0.78       329
   macro avg       0.19      0.16      0.16       329
weighted avg       0.70      0.78      0.73       329



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Confusion matrix

In [99]:
import matplotlib.pyplot as plt
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, rf_pred)

print(cm)

[[248  11   0   0   0   0   1   0]
 [ 24   8   0   0   0   1   0   0]
 [  6   1   0   0   0   0   1   0]
 [  1   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0]
 [  7   1   0   0   0   0   0   0]
 [ 15   0   0   0   0   0   1   0]
 [  1   0   0   0   0   0   0   0]]


## Using Baseline Model

In [5]:
from bs4 import BeautifulSoup
from textblob import TextBlob
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
import pandas as pd 

#Label and file details load
df = pd.read_csv('/gdrive/My Drive/Machine Learning /master996.csv', header = None, encoding='latin1')
csvInput = df.values.tolist()

#Please change file path
file_path = '/gdrive/My Drive/Gutenberg_19th_century_English_Fiction'

print(csvInput)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[['Book_Name;book_id;guten_genre;Author_Name'], ['The Mystery of the Boule Cabinet: A Detective Story;pg10067.epub;Detective and Mystery;Stevenson| Burton Egbert'], ['The Pupil;pg1032.epub;Literary;James| Henry'], ["At Love's Cost;pg10379.epub;Literary;Garvice| Charles"], ['The Heart of the Range;pg10473.epub;Western Stories;White| William Patterson'], ['The Worshipper of the Image;pg10812.epub;Literary;Gallienne| Richard Le'], ['The Book-Bills of Narcissus - An Account Rendered by Richard Le Gallienne;pg10826.epub;Literary;Gallienne| Richard Le'], ['Elusive Isabel;pg10943.epub;Detective and Mystery;Futrelle| Jacques'], ["Joe Burke's Last Stand;pg11004.epub;Literary;Wetterau| John Moncure"], 

#Preparing the data

In [17]:
index = 0
books = []
labels = []
i = 0
for book_details in csvInput:
    if index == 0:
      index = index + 1
      continue
    print(book_details)
    #Getting the file name from CSV
    a_split = book_details[0].split(';')
    file_name = a_split[1]
    if "." in a_split[1]:
      file_name = file_name.split('.')[0]
    #attaching the filename to filepath
    file_path_new = file_path +'/'+ file_name + '-content.html'
    #Loading HTML content
    html = open(file_path_new, encoding="UTF-8").read()
    soup = BeautifulSoup(html, features="lxml").text
    books.append(soup)
    labels.append(a_split[2])


['The Mystery of the Boule Cabinet: A Detective Story;pg10067.epub;Detective and Mystery;Stevenson| Burton Egbert']
['The Pupil;pg1032.epub;Literary;James| Henry']
["At Love's Cost;pg10379.epub;Literary;Garvice| Charles"]
['The Heart of the Range;pg10473.epub;Western Stories;White| William Patterson']
['The Worshipper of the Image;pg10812.epub;Literary;Gallienne| Richard Le']
['The Book-Bills of Narcissus - An Account Rendered by Richard Le Gallienne;pg10826.epub;Literary;Gallienne| Richard Le']
['Elusive Isabel;pg10943.epub;Detective and Mystery;Futrelle| Jacques']
["Joe Burke's Last Stand;pg11004.epub;Literary;Wetterau| John Moncure"]
['O+F;pg11005.epub;Literary;Wetterau| John Moncure']
['Polly and the Princess;pg11259.epub;Literary;Dowd| Emma C.']
["Maggie Miller: The Story of Old Hagar's Secret;pg11280.epub;Literary;Holmes| Mary Jane"]
['The Obstacle Race;pg11520.epub;Literary;Dell| Ethel M.']
['From out the Vasty Deep;pg11581.epub;Literary;Lowndes| Marie Belloc']
['Fate Knocks at 

In [29]:
for i in range(len(labels)):
    if labels[i] == "Literary":
      labels[i] = 1
    elif labels[i] == "Detective and Mystery":
      labels[i] = 2
    elif labels[i] == "Western Stories":
      labels[i] = 3   
    elif labels[i] == "Ghost and Horror":
      labels[i] = 4  
    elif labels[i] == "Humorous and Wit and Satire":
      labels[i] = 5
    elif labels[i] == "Christmas Stories":
      labels[i] = 6
    elif labels[i] == "Love and Romance":
     labels[i] = 7
    elif labels[i] == "Sea and Adventure":
      labels[i] = 8
    elif labels[i] == "Allegories":
      labels[i] = 9
    elif labels[i] == "All":
      labels[i] = 10

In [112]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(books, labels, test_size=0.33, random_state=45)

In [113]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(sublinear_tf=True, max_df=0.8,
                                 stop_words='english')
x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

In [115]:
type(x_train)

scipy.sparse.csr.csr_matrix

In [52]:
from sklearn.svm import SVC
from sklearn import metrics


non_linear_svm = SVC(C = 100, kernel='rbf', gamma=0.9)

non_linear_svm.fit(x_train, y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.9, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [53]:
svm_pred = non_linear_svm.predict(x_test)
svm_score = metrics.accuracy_score(y_test, svm_pred)
print(svm_score)

0.8297872340425532


In [116]:
from sklearn.metrics import classification_report
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           1       0.85      0.99      0.92       260
           2       0.90      0.58      0.70        33
           3       1.00      0.12      0.22         8
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         8
           8       1.00      0.25      0.40        16
           9       0.00      0.00      0.00         1

    accuracy                           0.86       329
   macro avg       0.47      0.24      0.28       329
weighted avg       0.84      0.86      0.82       329



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [117]:
import matplotlib.pyplot as plt
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, svm_pred)

print(cm)

[[258   2   0   0   0   0   0   0]
 [ 14  19   0   0   0   0   0   0]
 [  7   0   1   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0]
 [  8   0   0   0   0   0   0   0]
 [ 12   0   0   0   0   0   4   0]
 [  1   0   0   0   0   0   0   0]]
